spring.application.name=mockitoJunit

spring.datasource.url=jdbc:postgresql://localhost:5432/doctor
spring.datasource.username=postgres
spring.datasource.password=password

# Optional: schema initialization
spring.jpa.hibernate.ddl-auto=update

# JPA dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Show SQL in console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ? DO NOT ENABLE SSL LOCALLY
spring.datasource.hikari.data-source-properties.ssl=false
spring.datasource.hikari.data-source-properties.sslmode=disable